name: Deploy Hugo site to GitHub Pages

on:
  # Roda quando há um push para a branch especificada (geralmente main ou master)
  push:
    branches:
      - master # Mude para 'master' se essa for sua branch principal
  # Permite que você rode este workflow manualmente pela aba Actions no GitHub
  workflow_dispatch:

# Permissões para o GITHUB_TOKEN para permitir o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente, cancelando execuções em progresso do mesmo grupo/PR
concurrency:
  group: "pages"
  cancel-in-progress: true

# Variáveis de ambiente padrão para todos os jobs
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest # Usa a última versão estável do Ubuntu
    env:
      HUGO_VERSION: 0.121.2 # Especifique a versão do Hugo que você usa. 'latest' também funciona.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # Essencial para buscar temas adicionados como submódulos
          fetch-depth: 0        # Necessário para recursos do Hugo como .Lastmod ou .GitInfo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3 # Ação popular e confiável para Hugo
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true # Mude para false se você não usa a versão "extended" do Hugo

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5 # Configura o ambiente para GitHub Pages

      - name: Build with Hugo
        run: hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/" # Usa a baseURL fornecida pelo configure-pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Faz o upload do site gerado (pasta public/)
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Este job só roda depois que o job 'build' for concluído
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Ação oficial para deploy no GitHub Pages